### ISSUE TITLE
Weekly review checklist

### ISSUE THREAD

**Issue by DanicoSantos** [DanicoSantos/Getting-Things-Done#2]
## GET CLEAR
- [ ] Collect loose papers and materials
- [ ] Get your "In" to zero
- [ ] Empty your head (process any new projects, actions, Waiting Fors, someday's etc)
## GET CURRENT
- [ ] Review Next Actions lists
- [ ] Review previous calendar data
- [ ] Review upcoming calendar
- [ ] Review Waiting For list
- [ ] Review Projects lists
- [ ] Review any relevant checklists
## GET CREATIVE
- [ ] Review Someday/Maybe list
- [ ] Be creative and courageous
