### ISSUE TITLE
Daily review checklist

### ISSUE THREAD

**Issue by DanicoSantos** [DanicoSantos/Getting-Things-Done#3]
- [ ] Step 1: Review your calendar
- [ ] Step 2: Do an emergency scan (new inputs, urgent requests)
- [ ] Step : Check your Next Actions list
- [ ] Step 4: Set aside "clarifying time" in your calendar
- [ ] Step 5: Identify and address you limiting criteria (Context, time available, energy, priority)
